# Generated by Django 3.2.12 on 2022-03-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='用户密码')),
                ('rid', models.DecimalField(choices=[('会员', 1), ('管理员', 0), ('开发员', 9)], db_column='quanxian', decimal_places=0, max_digits=9, verbose_name='权限')),
                ('emial', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('token', models.CharField(max_length=128, verbose_name='token令牌')),
                ('CreatTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('LoginTime', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
            ],
        ),
    ]
