# Generated by Django 3.2.12 on 2022-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='user',
            name='rid',
            field=models.DecimalField(choices=[(0, '会员'), (5, '管理员'), (9, '开发人员')], db_column='quanxian', decimal_places=0, max_digits=9, verbose_name='权限'),
        ),
    ]
