# Generated by Django 3.2.12 on 2022-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20220305_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userproject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='项目id')),
                ('ProjectName', models.CharField(max_length=64, verbose_name='项目名')),
                ('fid', models.DecimalField(decimal_places=0, max_digits=10000, verbose_name='项目属于者')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='rid',
            field=models.DecimalField(choices=[(0, '会员'), (5, '管理员'), (9, '开发人员')], decimal_places=0, max_digits=9, verbose_name='权限'),
        ),
    ]
