# Generated by Django 3.2.12 on 2022-03-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20220305_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproject',
            options={'verbose_name_plural': '用户项目列表'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
