# Generated by Django 3.2.12 on 2022-03-05 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20220305_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproject',
            options={'verbose_name_plural': '项目列表'},
        ),
        migrations.AddField(
            model_name='userproject',
            name='CreatTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproject',
            name='LoginTime',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
